### ISSUE TITLE
insert image

### ISSUE THREAD

**Issue by Anichki** [Anichki/jemomgebrishvili#1]
შენი ტელეფონის ვიზუალში, ჩადე იმიჯი html-ში, position: absolute -თან შეხება თუ არ გქონია, რაც დაგჭირდება იმისთვის, რომ ფოტოზე ზედ გადაალაგო შენი ელემენტები. ნახავ როგორ მუშაობს css property "position".

**Comment by developer--** [comment]
მასე ვაკეთებდი და რაგაცამ გამჭედა. ალბათ ფოტოშოპში ვერ დავამუშავე კარგად ფოტო :/ ინსერტს რომ ვ აკეთებდი image _ს png კი იყო მარა რაგაცა სჭირდა, float left რომ ვაძლევდი ფოტო მაინც ნახევრად ჩანდა სანამ ზომას არ გავუზრდიდი. იმხელა ზომას ვაძლევდი რომ გამოჩენილიყო რაც რეალურად არ სჭირდებოდა

**Comment by Anichki** [comment]
როდესაც image ხმარობ html-ში წესით და რიგირთ თუკი იდეალურად გინდა ჩანდეს ზუსტად იმ ზომის უნდა იყოს (widht: ?px; height: ?px) რა ზომისაც მშობელი div არის, ანუ ის კონტეინერი რა ზმოისაც არის. აი მაინც შეიტანე შენ როგორც ფიქრობ თუნდაც გაჭედილი, რომ მე შემძლეოს ვნახო რა არის გასასწორებელი და მიგიწერ.

**Comment by Anichki** [comment]
იცი რა გააკეთე: 1. font-face და აუცილებლად დირექტორიების და ფოლდერების სტრუქტურას მიაქციე ყურადღება, java-ს შემთხვევაში მუშაობის პროცესში იმდენი ფაილი გროვდება თუ არ დააჯგუფე მერე ძალიან რთულია მოსაძიებლად და სხვისთვისაც ვისაც შენ დოკუმენტებთან ექნება შეხება. მაგ.: css - ჩადე css ფოლდერში, ანუ ლოგიკური სახელების დარქმევა და დირექტორიების სტრუქტურა აუცილებლად ნდა გაითვალისწინო

**Comment by developer--** [comment]
ეს კი ზოგადად მოწესრიგებულად ვაკეთებ ხოლმე :)

2015-04-26 23:04 GMT+04:00 Ani notifications@github.com:
