### ISSUE TITLE
just question

### ISSUE THREAD

**Issue by Anichki** [Anichki/jemomgebrishvili#4]
თუკი ამ ყველაფრის გარჩევას ზოგადად არ აპირებ ან არ გაინტერესებს მომწერე, რომ მე ამდენი დრო ტყუილად არ დავკარგო ხოლმე :)

სხვა შემთხვევაში პრობლემა არ არის ნებისმიერი დეტალი შემიძლია აგიხსნა, განახო ლინი მოგცე სად ნახო და კონკრეტულად რა.

**Comment by developer--** [comment]
დიდი მადლობა ასეთი ყურადღებისთვის. ბოდიში ვერ მოვახერხე მოცლა და კოდის გადაკეთება. არ იფიქრო რომ არ მაინტერესებს. გაწეწილი გრაფიკი მაქვს ერთი კვირაა. ჯეოლაბში ანდროიდზე ვარ მაგრამ ზოგადად ვები ძალიან მაინტერესებს. ვარჩევ სხვადასხვა ტექნოლოგიებს ( angular-js მა მომხიბლა :3 ).მაგრამ უფრო მეტად back-end მიზიდავს. რჩევებს აუცილებლად გავითვალისწინებ და სორსსაც გავარჩევ რაც მომეცი.
