### ISSUE TITLE
1. resolve error

### ISSUE THREAD

**Issue by Anichki** [Anichki/jemomgebrishvili#5]
ერთი იმიჯი, რომელიც გაწერილი გაქვს არ გიდევს პროექტში და შესაბამისად კონსოლში ერორია რადგან ვერ პოულობს იმიჯს.

**Comment by developer--** [comment]
უი დამვიწყებია ჩავაგდებ. სხვა ყველაფერი რაც ლოკალურად ჩავასწორე ჩემთან მანდაც ჩავასწორე

**Comment by developer--** [comment]
ანი ამ რეპოზიტორში არ შემიძლია ფაილის დამატება? img ს ვერ ვამატებ
