### ISSUE TITLE
2. საგამოცდო დავალება

### ISSUE THREAD

**Issue by Anichki** [Anichki/jemomgebrishvili#6]
index html-ში main-ში განათვასე image, ნავიგაციის დაბლა მწვანე ფერის მაგივრად რომ იყოს.
ამისთვის დაგჭირდება position - relative, absolute და z-index, რაც შეგიძლია დაგუგლო :)

**Comment by developer--** [comment]
გამოგიგზავნე ლინკი რეპოზიტორის. ოღონდ სხვა პროექტია.

**Comment by developer--** [comment]
ბრაიზერის ბოლომდე შემცირების შემდგე გამოდის მობილურის მენიუ
